"use client";

import Link from "next/link";
import { HEDERA_TESTNET, testnetDeployment } from "@sh/sdk";
import type { NextPage } from "next";

/** Feature status as tracked in docs/BUILD_STATE.md. Update both together. */
const FEATURES: [string, string][] = [
  ["ConsumerAccount + factory (Sourcify verified)", "VERIFIED_TESTNET"],
  ["Sponsored execution (zero-HBAR controller)", "VERIFIED_TESTNET"],
  ["Payments + signed payment requests (QR/link)", "VERIFIED_TESTNET"],
  ["HIP-904 airdrop action", "VERIFIED_TESTNET"],
  ["SaucerSwap swap-to-pay", "VERIFIED_TESTNET"],
  ["Session policy + red-team denials", "VERIFIED_TESTNET"],
  ["Network fees counted against agent caps", "VERIFIED_TESTNET"],
  ["Supra USD oracle for session caps", "VERIFIED_TESTNET"],
  ["HCS policy audit", "VERIFIED_TESTNET"],
  ["x402 exact / transferExecutor (facilitator + client)", "VERIFIED_TESTNET"],
  ["MCP server for AI agents", "VERIFIED_TESTNET"],
  ["HSS recurring payments (HIP-1215)", "VERIFIED_TESTNET"],
  ["Savings vault (agents deposit, never withdraw)", "VERIFIED_TESTNET"],
  ["Token launchpad: bonding curve, graduation into SaucerSwap", "VERIFIED_TESTNET"],
  ["HIP-904 claim by the recipient (Claim page)", "VERIFIED_TESTNET"],
  ["Guardian recovery (Recovery page)", "VERIFIED_TESTNET"],
  ["Custom action modules + yarn new:action (launchpad-buy)", "VERIFIED_LOCAL"],
  ["Vault yield strategy", "BLOCKED_EXTERNAL"],
];

const badge = (s: string) =>
  s === "VERIFIED_TESTNET"
    ? "badge-success"
    : s === "VERIFIED_LOCAL"
      ? "badge-info"
      : s === "BLOCKED_EXTERNAL"
        ? "badge-error"
        : "badge-ghost";

const DeveloperPage: NextPage = () => {
  const d = testnetDeployment;
  return (
    <div className="px-4 py-10 max-w-4xl mx-auto w-full flex flex-col gap-6 text-sm">
      <h1 className="text-2xl font-bold">Developer</h1>
      <section className="card bg-base-100 shadow p-4 gap-1">
        <h2 className="font-semibold">Network</h2>
        <div>Hedera testnet · chain {HEDERA_TESTNET.chainId}</div>
        <div>RPC {HEDERA_TESTNET.rpcUrl}</div>
        <div>Mirror {HEDERA_TESTNET.mirrorUrl}</div>
      </section>
      <section className="card bg-base-100 shadow p-4 gap-1">
        <h2 className="font-semibold">Deployments (packages/sdk/deployments/testnet.json)</h2>
        {d.factory ? (
          <>
            <div>
              Factory{" "}
              <a
                className="link"
                href={`${HEDERA_TESTNET.hashscan}/contract/${d.factoryContractId ?? d.factory}`}
                target="_blank"
                rel="noreferrer"
              >
                {d.factoryContractId} ({d.factory})
              </a>
            </div>
            <div>HCS audit topic {d.auditTopicId ?? "—"}</div>
            {Object.entries(d.tokens ?? {}).map(([k, t]) => (
              <div key={k}>
                {k}: {t.tokenId} ({t.decimals} decimals){t.label ? ` — ${t.label}` : ""}
              </div>
            ))}
            {d.saucerswap ? (
              <div>
                SaucerSwap V2 router {d.saucerswap.router}, quoter {d.saucerswap.quoter}
              </div>
            ) : null}
            <div>
              Oracle:{" "}
              {d.oracle
                ? `${d.oracle.contractId ?? d.oracle.address} — ${d.oracle.label}`
                : "none (session spend fails closed)"}
            </div>
            {d.vaults?.WHBAR ? (
              <div>Savings vault (WHBAR): {d.vaults.WHBAR.contractId ?? d.vaults.WHBAR.address}</div>
            ) : null}
            {d.launchpad ? <div>Token launchpad: {d.launchpad.contractId ?? d.launchpad.address}</div> : null}
            <div>
              x402: <code>/api/x402/premium</code> (paid resource), <code>/api/x402/facilitator/supported</code>
            </div>
            <div>
              MCP: <code>yarn mcp:start</code> with CONSUMER_ACCOUNT, AGENT_PRIVATE_KEY, CONSUMER_APP_URL
            </div>
          </>
        ) : (
          <div>
            Not deployed yet. Run <code>yarn bootstrap --fund</code>.
          </div>
        )}
      </section>
      <section className="card bg-base-100 shadow p-4 gap-2">
        <h2 className="font-semibold">Feature status</h2>
        {FEATURES.map(([f, s]) => (
          <div key={f} className="flex justify-between gap-2">
            <span>{f}</span>
            <span className={`badge ${badge(s)}`}>{s}</span>
          </div>
        ))}
        <p className="opacity-60 text-xs">
          Testnet proofs: TESTNET_VERIFICATION.md (generated by <code>yarn prove:testnet</code>).
        </p>
      </section>
      <section className="flex gap-3">
        <Link className="btn btn-sm" href="/debug">
          Debug contracts
        </Link>
        <Link className="btn btn-sm" href="/blockexplorer">
          Block explorer
        </Link>
      </section>
    </div>
  );
};

export default DeveloperPage;
