"use client";

import Link from "next/link";
import { HEDERA_TESTNET, testnetDeployment } from "@sh/sdk";
import type { NextPage } from "next";

/** Feature status as tracked in docs/BUILD_STATE.md. Update both together. */
const FEATURES: [string, string][] = [
  ["ConsumerAccount + factory", "VERIFIED_LOCAL"],
  ["Sponsored execution (zero-HBAR controller)", "VERIFIED_LOCAL"],
  ["Payments + signed payment requests (QR/link)", "VERIFIED_LOCAL"],
  ["HIP-904 airdrop action", "VERIFIED_LOCAL"],
  ["SaucerSwap swap-to-pay", "VERIFIED_LOCAL"],
  ["Session policy + red-team denials", "VERIFIED_LOCAL"],
  ["HCS policy audit", "VERIFIED_LOCAL"],
  ["Guardian recovery", "VERIFIED_LOCAL"],
  ["x402 transferExecutor (contract side)", "VERIFIED_LOCAL"],
  ["x402 facilitator support for transferExecutor", "BLOCKED_EXTERNAL"],
  ["USD price oracle for session caps", "BLOCKED_EXTERNAL"],
  ["HSS recurring payments", "EXPERIMENTAL"],
  ["Vault / launchpad recipes", "EXPERIMENTAL"],
];

const badge = (s: string) =>
  s === "VERIFIED_TESTNET"
    ? "badge-success"
    : s === "VERIFIED_LOCAL"
      ? "badge-info"
      : s === "BLOCKED_EXTERNAL"
        ? "badge-error"
        : "badge-ghost";

const DeveloperPage: NextPage = () => {
  const d = testnetDeployment;
  return (
    <div className="px-4 py-10 max-w-4xl mx-auto w-full flex flex-col gap-6 text-sm">
      <h1 className="text-2xl font-bold">Developer</h1>
      <section className="card bg-base-100 shadow p-4 gap-1">
        <h2 className="font-semibold">Network</h2>
        <div>Hedera testnet · chain {HEDERA_TESTNET.chainId}</div>
        <div>RPC {HEDERA_TESTNET.rpcUrl}</div>
        <div>Mirror {HEDERA_TESTNET.mirrorUrl}</div>
      </section>
      <section className="card bg-base-100 shadow p-4 gap-1">
        <h2 className="font-semibold">Deployments (packages/sdk/deployments/testnet.json)</h2>
        {d.factory ? (
          <>
            <div>
              Factory{" "}
              <a
                className="link"
                href={`${HEDERA_TESTNET.hashscan}/contract/${d.factoryContractId ?? d.factory}`}
                target="_blank"
                rel="noreferrer"
              >
                {d.factoryContractId} ({d.factory})
              </a>
            </div>
            <div>HCS audit topic {d.auditTopicId ?? "—"}</div>
            {Object.entries(d.tokens ?? {}).map(([k, t]) => (
              <div key={k}>
                {k}: {t.tokenId} ({t.decimals} decimals){t.label ? ` — ${t.label}` : ""}
              </div>
            ))}
            {d.saucerswap ? (
              <div>
                SaucerSwap V2 router {d.saucerswap.router}, quoter {d.saucerswap.quoter}
              </div>
            ) : null}
            <div>Oracle: {d.oracle ? d.oracle.label : "none (session spend fails closed)"}</div>
          </>
        ) : (
          <div>
            Not deployed yet. Run <code>yarn bootstrap --fund</code>.
          </div>
        )}
      </section>
      <section className="card bg-base-100 shadow p-4 gap-2">
        <h2 className="font-semibold">Feature status</h2>
        {FEATURES.map(([f, s]) => (
          <div key={f} className="flex justify-between gap-2">
            <span>{f}</span>
            <span className={`badge ${badge(s)}`}>{s}</span>
          </div>
        ))}
        <p className="opacity-60 text-xs">
          Testnet proofs: TESTNET_VERIFICATION.md (generated by <code>yarn prove:testnet</code>).
        </p>
      </section>
      <section className="flex gap-3">
        <Link className="btn btn-sm" href="/debug">
          Debug contracts
        </Link>
        <Link className="btn btn-sm" href="/blockexplorer">
          Block explorer
        </Link>
      </section>
    </div>
  );
};

export default DeveloperPage;
