import fs from "node:fs";
import path from "node:path";
import { HEDERA_TESTNET } from "@sh/sdk";
import { ROOT } from "./env";

export type FlowStatus = "PASS" | "FAIL" | "BLOCKED_EXTERNAL" | "NOT_RUN";

/** One proof entry (docs/BUILD_PROMPT §81). Every field is filled from observed network results only. */
export type Evidence = {
  flow: number;
  step: string;
  featureStatus: string;
  timestamp: string;
  actor: string;
  account: string;
  contract: string | null;
  asset: string | null;
  input: string;
  expected: string;
  actual: string;
  transactionHash: string | null;
  transactionId: string | null;
  mirrorQuery: string | null;
  mirrorResult: string | null;
  hcs: string | null;
  status: FlowStatus;
};

const hashscanTx = (id: string) => `${HEDERA_TESTNET.hashscan}/transaction/${id}`;

function row(e: Evidence): string {
  const tx = e.transactionId ?? e.transactionHash;
  const link = tx ? `[${tx}](${hashscanTx(tx)})` : "—";
  const mq = e.mirrorQuery ? `[query](${e.mirrorQuery})` : "—";
  return [
    `### ${e.flow}. ${e.step} — **${e.status}**`,
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Feature status | ${e.featureStatus} |`,
    `| Network | Hedera testnet (chain ${HEDERA_TESTNET.chainId}) |`,
    `| Timestamp | ${e.timestamp} |`,
    `| Actor | ${e.actor} |`,
    `| Account | ${e.account} |`,
    `| Contract | ${e.contract ?? "—"} |`,
    `| Asset | ${e.asset ?? "—"} |`,
    `| Input | ${e.input} |`,
    `| Expected | ${e.expected} |`,
    `| Actual | ${e.actual} |`,
    `| Transaction | ${link} |`,
    `| Mirror query | ${mq} |`,
    `| Mirror result | ${e.mirrorResult ?? "—"} |`,
    `| HCS reference | ${e.hcs ?? "—"} |`,
    "",
  ].join("\n");
}

export function writeVerification(entries: Evidence[], header: string): string {
  const file = path.join(ROOT, "TESTNET_VERIFICATION.md");
  const summary = entries.map(e => `| ${e.flow} | ${e.step} | ${e.status} |`).join("\n");
  const md = [
    "# Testnet verification",
    "",
    "Generated by `yarn prove:testnet` from live Hedera testnet observations. Nothing in this file is hand-written:",
    "every ID, hash and balance below was returned by the network or the Mirror Node during the run.",
    "",
    header,
    "",
    "| # | Flow | Result |",
    "| --- | --- | --- |",
    summary,
    "",
    ...entries.map(row),
  ].join("\n");
  fs.writeFileSync(file, md);
  return file;
}
