/**
 * yarn new:action <kebab-name>
 *
 * Scaffolds a custom typed action as an owner-installed planner module (contracts/interfaces/IActionModule.sol):
 *   packages/foundry/contracts/actions/<Name>Action.sol   module: ID + plan() (starts as a capped transfer)
 *   packages/foundry/test/actions/<Name>Action.t.sol      allowed path, cap denial, missing-permission denial
 *   packages/sdk/src/customActions/<name>.ts              action ID + actionData encoder/decoder
 *   packages/sdk/test/customActions/<name>.test.ts        encoder round trip
 *   docs/actions/<name>.md                                checklist for finishing the action
 * and registers the SDK module in packages/sdk/src/customActions/index.ts.
 *
 * The account's ownership, sponsorship, session policy, USD caps, fee accounting, receipts and HCS audit apply
 * unchanged: a module only plans; ConsumerAccount checks and executes. Nothing is deployed by this command.
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { ROOT } from "./lib/env";

const name = process.argv[2] ?? "";
if (!/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(name)) {
  console.error("usage: yarn new:action <kebab-name>   e.g. yarn new:action tip-jar");
  process.exit(1);
}
const parts = name.split("-");
const Pascal = parts.map(p => p[0]!.toUpperCase() + p.slice(1)).join("");
const camel = Pascal[0]!.toLowerCase() + Pascal.slice(1);
const CONST = parts.join("_").toUpperCase();
const actionId = `consumer.action.${name}.v1`;

const files: Record<string, string> = {
  [`packages/foundry/contracts/actions/${Pascal}Action.sol`]: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { IActionModule } from "../interfaces/IActionModule.sol";

/// @title ${Pascal}Action
/// @notice Typed action \`${actionId}\` (generated by \`yarn new:action ${name}\`).
/// @dev actionData = abi.encode(address asset, address to, uint256 amount). Starts as a capped transfer of the
///      account's HBAR (asset = address(0)) or an HTS token; replace plan() with the calls your action needs.
///      Declare the worst-case spend honestly: the account caps it and reverts if more of \`spendAsset\` leaves.
contract ${Pascal}Action is IActionModule {
    bytes32 public constant ID = keccak256("${actionId}");

    error InvalidInput();

    function plan(address, bytes calldata actionData)
        external
        pure
        returns (address spendAsset, address recipient, uint256 spendAmount, PlannedCall[] memory calls)
    {
        (address asset, address to, uint256 amount) = abi.decode(actionData, (address, address, uint256));
        if (to == address(0) || amount == 0) revert InvalidInput();
        calls = new PlannedCall[](1);
        calls[0] = asset == address(0)
            ? PlannedCall({ target: to, value: amount, data: "" })
            : PlannedCall({ target: asset, value: 0, data: abi.encodeWithSignature("transfer(address,uint256)", to, amount) });
        return (asset, to, amount, calls);
    }
}
`,
  [`packages/foundry/test/actions/${Pascal}Action.t.sol`]: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { ConsumerAccount } from "../../contracts/ConsumerAccount.sol";
import { ${Pascal}Action } from "../../contracts/actions/${Pascal}Action.sol";
import { AccountFixture } from "../ConsumerAccount.t.sol";

/// Generated by \`yarn new:action ${name}\`. Extend with every denial your action can produce.
contract ${Pascal}ActionTest is AccountFixture {
    ${Pascal}Action internal module;

    function setUp() public override {
        super.setUp();
        module = new ${Pascal}Action();
        _ownerSelfCall(abi.encodeCall(ConsumerAccount.setActionModule, (module.ID(), address(module))));
        bytes32[] memory actions = new bytes32[](1);
        actions[0] = module.ID();
        _grant(sessionKey, actions, new address[](0), 10e6, 25e6, uint64(block.timestamp + 1 days));
    }

    function test_sessionRunsWithinCaps() public {
        ConsumerAccount.SessionAction memory a = _action(module.ID(), abi.encode(address(usdc), merchant, uint256(5e6)));
        bytes memory sig = _signAction(a, sessionPk);
        vm.prank(relayer);
        account.executeSessionAction(a, sig);
        assertEq(usdc.balanceOf(merchant), 5e6);
        assertEq(account.getSession(sessionKey).spentTodayUsd6, 5e6);
    }

    function test_overCapDenied() public {
        ConsumerAccount.SessionAction memory a = _action(module.ID(), abi.encode(address(usdc), merchant, uint256(11e6)));
        bytes memory sig = _signAction(a, sessionPk);
        vm.expectRevert(ConsumerAccount.PerCallCapExceeded.selector);
        account.executeSessionAction(a, sig);
    }

    function test_sessionWithoutPermissionDenied() public {
        _grantDefaultSession();
        ConsumerAccount.SessionAction memory a = _action(module.ID(), abi.encode(address(usdc), merchant, uint256(1e6)));
        bytes memory sig = _signAction(a, sessionPk);
        vm.expectRevert(ConsumerAccount.ActionNotAllowed.selector);
        account.executeSessionAction(a, sig);
    }
}
`,
  [`packages/sdk/src/customActions/${camel}.ts`]: `import { type Address, type Hex, decodeAbiParameters, encodeAbiParameters, keccak256, toBytes } from "viem";

/** Typed action \`${actionId}\` (module: contracts/actions/${Pascal}Action.sol; generated by yarn new:action). */
export const ${CONST}_ACTION_ID: Hex = keccak256(toBytes("${actionId}"));

export type ${Pascal}Input = { asset: Address; to: Address; amount: bigint };

const params = [
  { type: "address", name: "asset" },
  { type: "address", name: "to" },
  { type: "uint256", name: "amount" },
] as const;

export const encode${Pascal} = (i: ${Pascal}Input): Hex => encodeAbiParameters(params, [i.asset, i.to, i.amount]);

export const decode${Pascal} = (data: Hex): ${Pascal}Input => {
  const [asset, to, amount] = decodeAbiParameters(params, data);
  return { asset, to, amount };
};
`,
  [`packages/sdk/test/customActions/${name}.test.ts`]: `import { describe, expect, it } from "vitest";
import { keccak256, toBytes } from "viem";
import { ${CONST}_ACTION_ID, decode${Pascal}, encode${Pascal} } from "../../src/customActions/${camel}";

describe("${name} action", () => {
  it("has the stable ID", () => {
    expect(${CONST}_ACTION_ID).toBe(keccak256(toBytes("${actionId}")));
  });

  it("round-trips actionData", () => {
    const input = {
      asset: "0x0000000000000000000000000000000000001549" as const,
      to: "0x1111111111111111111111111111111111111111" as const,
      amount: 123n,
    };
    expect(decode${Pascal}(encode${Pascal}(input))).toEqual(input);
  });
});
`,
  [`docs/actions/${name}.md`]: `# \`${actionId}\`

Generated by \`yarn new:action ${name}\`. A custom typed action is a planner module: the account owner installs it
with \`selfCall.setActionModule(account, ${CONST}_ACTION_ID, moduleAddress)\` and grants it to sessions like any
built-in action. ConsumerAccount charges the declared spend against the session's USD caps and recipient list,
executes the planned calls, rejects calls to itself or HTS, and reverts if more than the declared amount leaves.

## Checklist

- [ ] Define \`actionData\` in \`packages/foundry/contracts/actions/${Pascal}Action.sol\` and the SDK encoder.
- [ ] Implement \`plan()\`; declare the honest worst-case \`spendAsset\` / \`spendAmount\` / \`recipient\`.
- [ ] Tests: allowed path, every denial reason, owner path (\`packages/foundry/test/actions/${Pascal}Action.t.sol\`).
- [ ] Deploy the module and install it on the account (owner intent \`setActionModule\`).
- [ ] Add a step to \`scripts/prove-testnet.ts\` before claiming it works on Hedera.
`,
};

for (const rel of Object.keys(files)) {
  if (fs.existsSync(path.join(ROOT, rel))) {
    console.error(`refusing to overwrite ${rel}`);
    process.exit(1);
  }
}
for (const [rel, content] of Object.entries(files)) {
  const abs = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content);
  console.log(`created ${rel}`);
}
// Keep generated Solidity forge-fmt clean (skipped quietly if Foundry is not installed).
spawnSync("forge", ["fmt", `contracts/actions/${Pascal}Action.sol`, `test/actions/${Pascal}Action.t.sol`], {
  cwd: path.join(ROOT, "packages/foundry"),
  stdio: "ignore",
  shell: process.platform === "win32",
});
const barrel = path.join(ROOT, "packages/sdk/src/customActions/index.ts");
fs.appendFileSync(barrel, `export * from "./${camel}";\n`);
console.log("updated packages/sdk/src/customActions/index.ts");
console.log(`\nNext: implement plan(), then \`yarn foundry:test --match-contract ${Pascal}ActionTest\` and \`yarn sdk:test\`.`);
